DmaMgr_SendRequest2 = 0x80000D28;
Interface_LoadItemIcon1 = 0x8006FB50;
Interface_LoadItemIcon2 = 0x8006FC00;

Construct_Icon_Start = 0x800E1D9C;
Construct_Icon_Target = 0x800E1E90;

sEquipAnimState = 0x80829710;
sEquipAnimTimer = 0x80829714;
sEquipAnimNumFrames = 0x80829718;

sSoundParam1 = 0x80104394;
sSoundParam34 = 0x801043A0;
sSoundParam5 = 0x801043A8;

Audio_PlaySoundGeneral = 0x800C806C;
//KaleidoScope_UpdateEquipAnim = 0x8081AA60;
