include ../../toolchain/make/main.mk

ACTORNAME = BossRunningMan
ACTORNUM = 115
OBJECTNUM = 59

default: copyactor copyobject

$(ACTORNAME).o: BossRunningMan.h bossrunningmanobj.h

include ../../toolchain/make/actor.mk
