SCENEDIR = "../../build-romhack/scene/39 - House - Twins"

.PHONY: default clean

default:
	cp scene.zscene room_*.zmap conf.txt $(SCENEDIR)

clean:
	rm -rf $(SCENEDIR)/scene.zscene $(SCENEDIR)/room_*.zmap $(SCENEDIR)/conf.txt
