extern SCmdBase ChamberOfSages_scene_header00[];
extern ActorEntry ChamberOfSages_scene_header00_startPositionList[];
extern RomFile ChamberOfSages_scene_roomList[];
extern EntranceEntry ChamberOfSages_scene_header00_entranceList[];
extern LightSettings ChamberOfSages_scene_header00_lightSettings[1];
extern u32 ChamberOfSages_polygonTypes[];
extern CollisionPoly ChamberOfSages_polygons[];
extern Vec3s ChamberOfSages_vertices[349];
extern CollisionHeader ChamberOfSages_collisionHeader;
