include ../../toolchain/make/main.mk

ACTORNAME = betagreatfairy
ACTORNUM = 6
LDFLAGS += -T ../../scene/UnicornFountain/UnicornFountain_scene.out.ld

default: copyactor

include ../../toolchain/make/actor.mk
