AnimationContext_AddEntry = 0x8008B48C;
AnimationContext_SetLoadFrame = 0x8008B4C4;

_link_animetionSegmentRomStart = 0x00557000;

Player_RAM_START = 0x80388B60; /* Loaded/reloc'd RAM addr of start of Link overlay */
Player_START = 0x808301C0; /* VRAM addr of start of Link overlay */
Player_SetUpCutscene = 0x80850EC0;

csActionToLinkActionTable = 0x8085267C;
linkActionInitTable = 0x808529C8;
linkActionRunTable = 0x80852D00;
